# Generated by Django 2.2.8 on 2021-01-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
